### ISSUE TITLE
FR-03 Principals Components

### ISSUE THREAD

**Issue by JStockwell** [JStockwell/Acme-One-E8.02#58]
Operations by all principals on components:
- List the components that have been published.
- Show the details of a component that he or she can list.

**Comment by JStockwell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DP2-620f5218cba8980012d7ab8d/issues/JStockwell/Acme-One-E8.02/58?planning-poker) with ZenHub @alegestor @ferclabar @GregoOS @Mancabm @Pablosancval

**Comment by GregoOS** [comment]
Done
