### ISSUE TITLE
FR-06 Principals Announcements

### ISSUE THREAD

**Issue by JStockwell** [JStockwell/Acme-One-E8.02#61]
Operations by authenticated principals on announcements:
- List the announcements that are not older than one month.
- Show the details of the announcements that they can list.

**Comment by JStockwell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DP2-620f5218cba8980012d7ab8d/issues/JStockwell/Acme-One-E8.02/61?planning-poker) with ZenHub @alegestor @ferclabar @GregoOS @Mancabm @Pablosancval

**Comment by GregoOS** [comment]
Done
