### ISSUE TITLE
FR-12 Inventors Patronages Report

### ISSUE THREAD

**Issue by JStockwell** [JStockwell/Acme-One-E8.02#67]
Operations by inventors on patronage reports:
- List the patronage reports associated with their patronages.
- Show the patronage reports that they can list.

**Comment by JStockwell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DP2-620f5218cba8980012d7ab8d/issues/JStockwell/Acme-One-E8.02/67?planning-poker) with ZenHub @alegestor @ferclabar @GregoOS @Mancabm @Pablosancval

**Comment by alegestor** [comment]
Authorise in Show should use the function indicated by the teacher. I cannot remember the exact function but it was something like request.isActive(). Check the follow up notes
